### ISSUE TITLE
Question: How do I bind to public packages?

### ISSUE THREAD

**Issue by jzaccone** [openwhisk/openwhisk-wskdeploy#142]
How can I use the manifest.yml or deployment.yml to bind to public packages with my custom parameters? Let me know if there is some docs that I am missing.

```
  wsk package bind /whisk.system/cloudant my-bound-package-name \
    --param username john
```

**Comment by paulcastro** [comment]
That feature is not supported, though we opened an issue related to this -- #41.  The proposal is to add a dependency key to the manifest.yaml file, this will allow you to specify external package entities in the manifest.  There an open question now on how best to declare that the dependency is shared rather than some code in a github repo.

**Comment by jzaccone** [comment]
Thank you for the quick response. Closing this issue.
