### ISSUE TITLE
Add support for web actions

### ISSUE THREAD

**Issue by cjelger** [openwhisk/openwhisk-wskdeploy#233]
It would be great if wskdeploy would support web actions (like wsk does).

cc: @paulcastro as discussed on slack

**Comment by lzbj** [comment]
ok, I'll investigate this one.

**Comment by paulcastro** [comment]
@lzbj we have code now that can read annotations in a deployment file.  We should probably copy this code into the manifest reader and refactor the deployment file code to only add new annotations or overwrite existing ones from the manifest.

After that, one way to support web-export is simply make it an annotation:


```
actions:
    myAction:
         annotations:
                 web-export: true
```

@starpit had some thoughts about this model.  While we use annotations in the REST API to set web-export, we might want to support a higher level key in the manifest instead of exposing annotations, for example one way (maybe not a great way):

```
actions:
      myAction:
           web-export: true
```

**Comment by cjelger** [comment]
By the way, the first proposal from @paulcastro is exactly how they do in serverless, see https://serverless.com/framework/docs/providers/openwhisk/guide/web-actions/

**Comment by lzbj** [comment]
Just my personal view, the second one is more intuitive and reasonable.

**Comment by mrutkows** [comment]
Thanks David. Indeed, mainstreamed features should not be handled via annotations (although this may be the case) and reflecting them in the YAML as an attribute (key) of an Action would also be my preference.

**Comment by mrutkows** [comment]
@cjelger support also added to the 0.8.4 spec.  https://github.com/openwhisk/openwhisk-wskdeploy/blob/master/specification/openwhisk_v0.8.4.pdf

**Comment by lzbj** [comment]
close as merged.

**Comment by cjelger** [comment]
Thank you all for that very useful feature!
